# Final Project: Gendered Language Respository in Colonial Caribbean Historical texts from early 19th century.

This project seeks to collect and form a repository of gendered words of 3 colonial Caribbean primary sources. These 3 historical texts are:

"An Historical Account of the Black Empire of Hayti" by Marcus Rainsford

"The History, Civil and Commercial, of the British colonies in the West Indies" by Bryan Edward

"History of the island of St. Domingo, from its first discovery by Columbus to the present period" by Sir James Basket

This will be done in order to gain a deeper understanding gendered language during the colonial-Caribbean early 19th century. In addition, it may reveal larger colonial narratives about gender roles.

But how can can perceptions of gender be quantified from a historial text from the early 19th century? I plan to use SpaCy to tokenize the entirety of the 3 documents. By doing so, I will be able to extract the number of times gendered words are stated. Later, I will visual this using pandas. Then I will use chi-sqaure test to find the signifigance of the ratios I calculate. I hypothesize this to reveal that women will mainly be mentioned in virtue of their relationship to men. In other words, women will be most commonly be mentioned in the text as a title of "wife", "mother", or "daughter". In contrast, I expect that men will not be mentioned as often in relation to their status as a "husband', "father", or "son" but more commonly as simply "men".

First, we must upload our packages and our the text file for "An Historical Account of the Black Empire of Hayti." Natural Language Processors(NLP) are created to understand and interpret human language. In order for this text to be tokenized, I will use the NLP called SpaCy. I will also import Pandas to be able to minipulate the data later on and create tables.

In [1]:
import spacy
import pandas as pd
data = [10, 20, 30]
s = pd.Series(data, index=['a', 'b', 'c'])

try:
      nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading language model...")
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

print("✅ Libraries imported and Model loaded!")

✅ Libraries imported and Model loaded!


It is key to ensure that as I work with each text, I assign unique variables for each text file. This way, I can ensure the data will be processed seperately. Code involing Rainford's text will be marked using the letter "R" in the begining of the variable name. "E" will be used for code involving the analysis of Edwards' text. "B" will be placed in front of variables concerning itself with Basket's text.

# Rainsford "An Historical Account of the Black Empire of Hayti"

First we will open Rainsford's text and prepare it to be read by our Natural Language Processor, SpaCy.

In [2]:
with open("Rainsford_Full_Text.txt", "r", encoding="utf-8") as infile:
  R_full_text = infile.read()

print(f"Download complete. Total characters: {len(R_full_text)}")
print("-" * 50)
print(R_full_text[0:1000])

Download complete. Total characters: 601736
--------------------------------------------------
INTRODUCTION. 


It has frequently been the fate of striking events, and particularly those which 
have altered the condition of mankind, to be denied that consideration by 
their contemporaries, which they obtain from the veneration of posterity. In 
their vortex, attention is distracted by the effects; and distant society recedes 
from the contemplation of objects that threaten a violation of their system, 
or wound a favourite prejudice. It is thus that history, with all the advantages 
of calm discussion, is imperfect; and philosophy enquires in vain for the un- 
recorded causes of astonishing transactions. 

To remedy the evil in this enlightened æra, the disquisitions of the ob- 
server, and the relations of the traveller occur; but these are perused with the 
rapidity, with which they are necessarily made, and, although they teach us 
what regards our own nature, impress no other sense

In [3]:
print("Processing text pipeline... (this may take a moment)")
R_doc_full_text = nlp(R_full_text)

print("Processing complete!")
print(f"Processed {len(R_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 601736 characters from the full text.


### Quantifying Mentions of Female-related Terms in Rainsford

To quantify female-related terms, I will create a list of gendered terms related to women and namnameing the variable "female_terms". I then will create a table listing all moments these tokens are mentioned. This way, I can procure a count of the number of times each gender term is mentioned. I found that the easiest way to achieve this is through creating a loop. This way, the code will continuously parse through the text and look for words that will match my list, which will be be counted using "matching_female_tokens"

To create the dataframe, I will use a series using "matching_female tokens" as my data source. Modeling the Visualizing History notebook, I will use ".reset_index" to change my index into a column, making sure to name the column 'Counts'. However, in order for the table to generate correctly, I need to use ".value_counts()" similar to the bar graph generated in NER with SpaCy. This allows the code to understand that the index is the unique tokens and the counts are their unique values.

Then, I will give my table a name and print the top 20 instances of female related words.This will be repeated for each gendered repository and text.

In [4]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

R_matching_female_tokens = []
for token in R_doc_full_text:
    if token.text.lower() in female_terms:
        R_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        R_matching_female_tokens.append(token.lemma_.lower())

R_df_female_mentions = pd.Series(R_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(R_df_female_mentions.head(20))

Top mentions of female-related terms:


,index,Counts
0,mother,50
1,wife,16
2,women,15
3,female,11
4,woman,7
5,females,6
6,sister,6
7,lady,4
8,ladies,4
9,wives,3


In [5]:
print(f"Sum of all Rainsford female-related terms: {R_df_female_mentions['Counts'].sum()}")

Sum of all Rainsford female-related terms: 131


The table shows that mother and wife were the two most mentioned female-related terms in the text. These two terms dominate over half of the overall counts listed.
Now let's generate the counts of male-related terms in Rainsford's text using the same process, but different variables and terms.

### Quantifying Mentions of Male-related Terms in Rainsford

In [6]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

R_matching_male_tokens = []
for token in R_doc_full_text:
    if token.text.lower() in male_terms:
        R_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        R_matching_male_tokens.append(token.lemma_.lower())

R_df_male_mentions = pd.Series(R_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(R_df_male_mentions.head(20))

Top mentions of male-related terms:


,index,Counts
0,men,101
1,man,65
2,brother,28
3,son,12
4,father,12
5,brothers,11
6,sons,8
7,fathers,3
8,husband,3
9,husbands,2


In [7]:
print(f"Total count of all male-related terms: {R_df_male_mentions['Counts'].sum()}")

Total count of all male-related terms: 249


Out of approximately 200 counts, 15 of male-related terms contained refrence to being a "father(s)" and 5 mentions to being a "husband(s)". This is in comparison to women who are mentioned approximately over half of the time as either "mother(s)" or "wife(wives)"

Now that we have our data, we can now conduct a comparative analysis of the number of times female and male terms are used in the text. Again, the goal is to discover if female relational terms (mother, wife, daughter...) are used more than male relational terms (father, husband, son...).

### Quantitive Analysis of Gendered Terms in Rainsford

First, let's discover the relative frequency of female-related terms in Rainsford's text. This will give us a better idea of the signifigance of the terms. This will be done through simple division. I am defining the variables for my own understanding, so that I so not assign the wrong variable to a sum. The string's existance will not effect the code in any way. 

In [8]:
a = 'Rainsford total characters'
b = 'Sum of all Rainsford female-related terms'

a = 601736
b = 131

result = b / a
print(result)

0.00021770344470000132


Female-related terms are only mentioned in the entirety of Rainsford's text with a relative frequency of .022%

In [9]:
a = 'Rainsford total characters'
b = 'Sum of all Rainsford male-related terms'

a = 601736
b = 249

result = b / a
print(result)

0.0004138027307656514


In comparison, Male-related terms are mentioned in Rainsford's text with a relative frequency of .041%

Out of all the characters counted by SpaCy, female-related terms are mentioned .022% of the time and male-related terms are mentioned .041% of the time. Knowing this, we can see that gendered-language does not make up a large portion of Edwards' text. However, by looking at the interal ratios of each gender, perhaps we can discover that there is a dependant relationship between gender and relational-terms. 

This leads me into looking at the portion rational-terms out of total gendered-terms for females and males.

This will be acomplished by creating a list of female relational terms under a new variable. Then, I will extract the values using our previously collected data from the dataframe. This will allow me to see the total sum of relational terms such as mother, wife, and sister.

In [10]:
R_total_female_relational_terms = ['mother', 'mothers', 'wife', 'wives', 'sister', 'sisters', 'daughter', 'daughters']

R_total_female_relational_terms = R_df_female_mentions[R_df_female_mentions['index'].isin(R_total_female_relational_terms)]['Counts'].sum()

print(f"Sum of all Rainsford female relational terms: {R_total_female_relational_terms}")

Sum of all Rainsford female relational terms: 84


To generate the ratio of we will define each variable for my own understanding, and then divide the total number of relational female words to total female gendered words

In [11]:
a = 'Sum of all Rainsford female relational terms'
b = 'Sum of all Rainsford female-related terms'

a = 84
b = 131

result = a / b
print(result)

0.6412213740458015


In Rainsford's text, the female relational ratio is 64%. However, let's compare this to the male relational ratio. First, I will find the sum of all male relational terms used in Rainsford:

In [12]:
R_total_male_relational_terms = ['father', 'fathers', 'son', 'sons', 'husband', 'husbands', 'brother', 'brothers']

R_total_male_relational_terms = R_df_male_mentions[R_df_male_mentions['index'].isin(R_total_male_relational_terms)]['Counts'].sum()

print(f"Sum of all Rainsford male relational terms: {R_total_male_relational_terms}")

Sum of all Rainsford male relational terms: 79


Now I will discover the male relational ratio and see the frequency of relationals male terms such as 'father', 'son', and 'husband'.

In [13]:
a = 'Sum of all Rainsford male relational terms'
b = 'Sum of all Rainsford male-related terms'

a = 79
b = 249

result = a / b
print(result)

0.3172690763052209


In Rainsford's text, the male relational ratio is 32% 

Just from the percentages, we can see a disparity in the way women and men are refered to in Rainsford's text. Women are refered to using relational terms 64% of the time compared to men being refered to by relational terms 32% of the time.

But, is this signifigant? I will use a chi-square test to determine the signifigance of use of relational terms for each gender. I will be modeling the chi-square test shown in the in-class jupyter notebook "python for statistics". The chi-square table will allow me to test the null hypothesis that there is no relation between gender and relational terms. 

To run this command, I will need to install a new package called scipy. Scipy allows for a special command called 'chi2_contingency' to be used to help streamline creating a chi-square table. To download this, I had to place '%' in front of the command to activate it in a notebook cell! I learned this from following a guide VS Code provides during a SyntaxError.

In [14]:
%pip install scipy

from scipy.stats import chi2_contingency

Note: you may need to restart the kernel to use updated packages.


Next, I simply inserted the corosponding values for each variable. To get the nonrelational-terms, I subtracted the rational terms sum by the total number of gendered terms for both female and male words. Then, I ensured I would have each of my 4 variables represented by labling the index 'relation' and 'nonrelation' and the columns 'female' and 'male'.

In [15]:
female_relational = 84
female_nonrelational = 47
male_relational = 79
male_nonrelational = 170

table = pd.DataFrame(
    [[female_relational, male_relational],
     [female_nonrelational, male_nonrelational]],
    index=['relation', 'nonrelational'],
    columns=['female', 'male']
)
display(table)

chi2, p, dof, expected = chi2_contingency(table)
print("chi2:", chi2)
print("p-value:", p)
print("expected:", expected)

,female,male
relation,84,79
nonrelational,47,170


chi2: 35.4657582236978
p-value: 2.595738473286046e-09
expected: [[ 56.19210526 106.80789474]
 [ 74.80789474 142.19210526]]


Awesome! A p-value < 0.05 means that the difference between the values is unlikely due to chance. In Rainsford's text, we can see that the p = ~0.00000026. This *much* less than 0.05. and is a sign to reject the null hypothesis. The null hypothesis was that the relationship between gender and relational-terms is independent

In addition, the expected values show up what the values should be if gender and relational-terms were independant. If these two veriables were independant, then relational female terms should be 56.19 instead of 84. Female nonrelations terms should be 74.81, not 47. Looking at language used for males, male relational terms were expected to be 106.81, not 79. Male nonrelational terms were expected to be 142.19 instead of 170.

## Rainsford Gendered Language Takeaways

Based on the chi-squared table, we can see that it is *extreamly unlikely* that gender and relational-terms are not related. The actual occurances of female relational terms is much higher than what was expected to occur in Rainsford text. Male relational terms were expected to be ~107, yet in actuality, males are refered as husband(s), father(s), brother(s), and son(s) only 32% of the time or on 79 specific instances. 

This provides strong evidence that the way gendered terms are used in Rainsford's text is not balanced. Women are referred to with relational language far more often than the chi-square model predicted and man appear in relational language far less than expected. 

At the begining of this project, I expected that women would be mentioned in historical caribbean texts by virtue of their relationship to men. According to the quantitative analysis I conducted, there is substancial evidence that there is disproportional representation of women in Rainsford's text. 

However, "An Historical Account of the Black Empire of Hayti" is only one subject of my analysis. To determine if my expectation is true or false, I will repeat this process on two more historial Caribbean texts written in the early 19th century by colonists. 

# Edwards "The History, Civil and Commercial, of the British colonies in the West Indies"

First, I will look at the number of female and male gender words used in Bryan Edwards' "The History, Civil and Commercial, of the British colonies in the West Indies."

Edwards wrote his text with a focus on the devlopment of the British West Indies. Instead of Haiti, Edwards looks primary at Jamaica. This is done to understand the history of British-colonial expansion in the Caribbeans. In addition, he documents the commercial history of the region, specifically looking at how the sugar industry, argiculture, and slave trade devloped between Britian, the United States, and Caribbean islands. 

Edwards' work has been used as a primary source in understanding overall trends in British Caribbean. Thus, I have chosen it to examine how it has protrayed female and males through the use of gendered langauge. I expect, similar to Rainsford, that women will be mentioned in virtue of their relationship to a man. This means that the frequency of female relational terms, such as mother, wife, and daughter, will be higher than the frequency of male relational terms.

To discover this, I will repeat the steps taken for Rainsford's text to tokenize Edwards' document to be read by SpaCy. 

In [16]:
with open("Edwards_Full_Text.txt", "r", encoding="utf-8") as infile:
  E_full_text = infile.read()

print(f"Download complete. Total characters: {len(E_full_text)}")
print("-" * 50)
print(E_full_text[0:500])

Download complete. Total characters: 706715
--------------------------------------------------
First'  arrival  of  the  English  at  this  islaad.— -Origin,  pro¬ 
gress,  and  termination  of  the  proprietary  government. 
Revenue  granted  to  the  crown  of  four  and  a  half  per 
centum  on  all  produce  exported — how  obtained.— Origin 
of  the  act  of  navigation. — Situation  and  extent  of  the 
island. — Soil  and  produce. — Population. — Decline,  and 
causes  thereof. — Exports  and  imports. 

THE  island  of  Barbadoes*  of  which  I  now  pro¬ 
pose  to  treat,  was


In [17]:
print("Processing text pipeline... (this may take a moment)")
E_doc_full_text = nlp(E_full_text)

print("Processing complete!")
print(f"Processed {len(E_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 706715 characters from the full text.


We can now begin creating a repository of gendered-language and examine if there is a relationship between gender and relational-terms.

### Quantifying Mentions of Female-related Terms in Edwards

Now, I will extract the same exact list of terms to ensure continuity between my subjects. Then, I will visualize the most commons female gendered terms used in Edwards' text using pandas. 

In [18]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

E_matching_female_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in female_terms:
        E_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        E_matching_female_tokens.append(token.lemma_.lower())

E_df_female_mentions = pd.Series(E_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(E_df_female_mentions.head(20))

Top mentions of female-related terms:


,index,Counts
0,women,27
1,woman,17
2,mother,15
3,females,15
4,wife,13
5,wives,11
6,ladies,5
7,female,5
8,girl,4
9,sister,3


In [19]:
print(f"Total count of all female-related terms: {E_df_female_mentions['Counts'].sum()}")

Total count of all female-related terms: 126


We can see that Edwards and Rainsford have had different frequencies of female-related terms. Non-relational female-related terms hold the top two spots. Edwards does have two more rows. These rows contain the words 'girl', 'girls' which were not mentioned in Rainsford's text. 

The total sums also differ by a count of 5 words.

### Quantifying Mentions of Male-related Terms in Edwards

In [20]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

E_matching_male_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in male_terms:
        E_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        E_matching_male_tokens.append(token.lemma_.lower())

E_df_male_mentions = pd.Series(E_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(E_df_male_mentions.head(20))

Top mentions of male-related terms:


,index,Counts
0,man,104
1,men,95
2,father,18
3,son,16
4,brother,16
5,males,12
6,boy,8
7,sons,8
8,boys,6
9,husband,4


In [21]:
print(f"Total count of all male-related terms: {E_df_male_mentions['Counts'].sum()}")

Total count of all male-related terms: 297


In Rainsford's text, male-related terms were used 249 times. In comparison, Edwards uses male-related terms 297 times. Edwards has 13 rows instead of Rainsford's 12 rows due to mentioning 'boys' 6 times in his work. 

So far, we have detected some interesting differences between the way gendered-langauge is used between the two texts. I will now begin my quantiative analysis to discover more about the way language is used in Edwards' text.

### Quantitive Analysis of Gendered Terms in Edwards

First, let's discover the relative frequency of female-related terms in Edwards' text. Like before, this will give us a better idea of the signifigance of the terms. 

In [22]:
a = 'Edwards total characters'
b = 'Sum of all Edwards female-related terms'

a = 706715
b = 126

result = b / a
print(result)

0.00017828969245028053


Female-related terms are only mentioned in Edwards with a relative frequency of .017%

In comparison, Rainsford had a relative frequency of .022%

In [23]:
a = 'Edwards total characters'
b = 'Sum of all Edwards male-related terms'

a = 706715
b = 297

result = b / a
print(result)

0.00042025427506137554


Male-related terms are mentioned in Edwards' text with a relative frequency of .042%, comparable with Rainsford's .041%

Out of all the characters counted by SpaCy, female-related terms are mentioned .017% of the time and male-related terms are mentioned .041% of the time. Knowing this, we can see that gendered-language does not make up a large portion of Edwards' text. However, by looking at the interal ratios of each gender, perhaps we can discover that there is a dependant relationship between gender and relational-terms. 

Let's begin by looking at female-related terms. I will create a new list containing all female relational-terms in Edwards. Like before, this will be given a new veriable name in order to locate relational-terms within the index of total female-related terms.

In [24]:
E_total_female_relational_terms = ['mother', 'mothers', 'wife', 'wives', 'sister', 'sisters', 'daughter', 'daughters']

E_total_female_relational_terms = E_df_female_mentions[E_df_female_mentions['index'].isin(E_total_female_relational_terms)]['Counts'].sum()

print(f"Sum of all Edwards female relational terms: {E_total_female_relational_terms}")

Sum of all Edwards female relational terms: 50


Alright. Now it's time to find the frequency of female-relational terms used in Edwards. Just as before, this will be done through simple division.

In [25]:
a = 'Sum of all Edwards female relational terms'
b = 'Sum of all Edwards female-related terms'

a = 50
b = 126

result = a / b
print(result)

0.3968253968253968


In Edwards' text, the female relational ratio is 40%. 

Let's compare this to the male relational ratio.

In [26]:
E_total_male_relational_terms = ['father', 'fathers', 'son', 'sons', 'husband', 'husbands', 'brother', 'brothers']

# Filter the DataFrame for these terms and sum their counts
E_total_male_relational_terms = E_df_male_mentions[E_df_male_mentions['index'].isin(E_total_male_relational_terms)]['Counts'].sum()

print(f"Sum of all Edwards male relational terms: {E_total_male_relational_terms}")

Sum of all Edwards male relational terms: 70


Now I will discover the male relational ratio and see the frequency of relationals male terms such as 'father', 'son', and 'husband'.

In [27]:
a = 'Sum of all Rainsford male relational terms'
b = 'Sum of all Rainsford male-related terms'

a = 70
b = 297

result = a / b
print(result)

0.2356902356902357


In Edwards' text, the male relational ratio is 24%.

The female and male relational term ratio is not as dramatic as the relational term ratio in Rainsford. By using the same chi-square test, the signifiance of relational gendered terms can be understood. The null hypothesis is the same, that there is no relation between gender and relational-terms. We will test for the p-value to determine if there is likely an independant relationship between gender and relational terms.

I am still using simple substraction to determine the number of nonrelational gendered words by subtracting the number of relational terms from the total number of gendered terms for male and female categories. 

In [28]:
female_relational = 50
female_nonrelational = 76
male_relational = 70
male_nonrelational = 227

table = pd.DataFrame(
    [[female_relational, male_relational],
     [female_nonrelational, male_nonrelational]],
    index=['relation', 'nonrelational'],
    columns=['female', 'male']
)
display(table)

chi2, p, dof, expected = chi2_contingency(table)
print("chi2:", chi2)
print("p-value:", p)
print("expected:", expected)

,female,male
relation,50,70
nonrelational,76,227


chi2: 10.524744840555485
p-value: 0.0011778667405495107
expected: [[ 35.74468085  84.25531915]
 [ 90.25531915 212.74468085]]


Interesting! A p-value < 0.05 means that the difference between the values is unlikely due to chance. In Edwards' text, we can see that the p = 0.00118. While not as extream as Raindford, this less still than 0.05 and is a sign to reject the null hypothesis. The null hypothesis is that the relationship between gender and relational-terms is independant. 

The expected values is what suprised me. I believed the values were already low, but the expected values were even lower for female relational terms(expected: 35.7; actual: 50) and male nonrelational-terms(expected: 212.7; actual: 227) 

The oposite was true for female nonrelational terms(expected: 90.3; actual: 76) and male relational terms(expected: 84.3; actual: 70).

## Edwards Gendered Language: Take-Aways

The chi-squared tests shows strong evidence against the claim that the relationship between gender and relational terms is independent. In fact, the difference between female and male usage of relational terms is statistically signifigant. 

While the p-value was not as extream as in Rainsford, it still is strong evidence which points to the idea that the relationship between gender and relational terms is dependant. It aids in proving my hypothesis as correct: that women are more often than not mentioned by virtue of their relationship with a man in Caribbean-colonial history books. 

There is still another primary source from this period I will be analyizing to see if it corroborates the evidence that has so far been shown against the null hypothesis. 

# Sir James Basket "History of the island of St. Domingo, from its first discovery by Columbus to the present period."

Sir James Basket's "History of the island of St. Domingo, from its first discovery by Columbus to the present period" was printed in 1818. Basket covers the discovery of St. Domingo by the Spanish crown and colonial rule. He also details slave rebellions and independence movements, highlighting the social and political shifts of the era. 

This text has been used as an important primary source surrounding Haitian history and recountment of the Haitian revolution. It covers histories of the Spanish side of the island, in addition to Saint-Domungue (present day Haiti).

Basket's document, like the others in my project, concern itself with representing colonial views on Caribbean history. It will be my 3rd document in examining the protrayal of females and males through the use of gendered langauge. I expect, similar to Rainsford and Edwards, that women will be mentioned in virtue of their relationship to a man. 

I will use the same methods used in the other two texts. By using the chi-square test, I expect to reject the idea that gender and relational terms are independant in the context of colonial Caribbean history.

First, we must prepare the document to be tokenized for textual analysis.

In [29]:
with open("Basket_Full_Text.txt", "r", encoding="utf-8") as infile:
  B_full_text = infile.read()

print(f"Download complete. Total characters: {len(B_full_text)}")
print("-" * 50)
print(B_full_text[0:200])

Download complete. Total characters: 650071
--------------------------------------------------
OF 

CHAPTER  I. 

FROM  THE  PERIOD  OF  THE  DISCOVERY  OF  THE  ISLAND,  TO 
THE  YEAR  1600. 

Situation. — General  description. — Discovery  hy  Columhus. — State  of 
theinhahitants. — Anecdote


In [30]:
print("Processing text pipeline... (this may take a moment)")
B_doc_full_text = nlp(B_full_text)

print("Processing complete!")
print(f"Processed {len(B_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 650071 characters from the full text.


### Quantifying Mentions of Female-related Terms in Basket

Now, I will determine the total number of female-related terms in Basket's text

In [31]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

B_matching_female_tokens = []
for token in B_doc_full_text:
    if token.text.lower() in female_terms:
        B_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        B_matching_female_tokens.append(token.lemma_.lower())

B_df_female_mentions = pd.Series(B_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(B_df_female_mentions.head(20))

Top mentions of female-related terms:


,index,Counts
0,mother,21
1,women,16
2,wife,16
3,wives,7
4,woman,4
5,daughters,3
6,females,3
7,female,2
8,daughter,2
9,mothers,2


In [32]:
print(f"Total count of all female-related terms: {B_df_female_mentions['Counts'].sum()}")

Total count of all female-related terms: 79


Basket has the lowest sum of total female-related terms at 79. In addition, 'monther' is the most mentioned female-related term. The words 'women' and 'wife' are tied for the same amount. This observation makes me think female-terms will disproportionately represent relational terms. 

### Quantifying Mentions of Male-related Terms in Basket

In [33]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

B_matching_male_tokens = []
for token in B_doc_full_text:
    if token.text.lower() in male_terms:
        B_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        B_matching_male_tokens.append(token.lemma_.lower())

B_df_male_mentions = pd.Series(B_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(B_df_male_mentions.head(20))

Top mentions of male-related terms:


,index,Counts
0,men,108
1,man,57
2,brother,35
3,son,16
4,sons,15
5,father,13
6,husband,9
7,male,7
8,fathers,7
9,brothers,6


In [34]:
print(f"Total count of all male-related terms: {B_df_male_mentions['Counts'].sum()}")

Total count of all male-related terms: 276


The sum of all male-related terms in Basket is similar to the sums counted in Rainsford and Edwards.

It looks as though the sum of the male-related terms is regular, and the sum of the female-related terms is less-than-normal.

### Quantitive Analysis of Gendered Terms in Basket

Time to find the relative frequency of female-related terms in Basket's text.

In [35]:
a = 'Basket total characters'
b = 'Sum of all Basket female-related terms'

a = 650071
b = 79

result = b / a
print(result)

0.00012152518724877744


Female-related terms are only mentioned in Basket with a relative frequency of .012%

In comparison, Rainsford had a relative frequency of .022% and Edwards with .017%

This is the lowest frequency out of all 3 texts.

In [36]:
a = 'Basket total characters'
b = 'Sum of all Basket male-related terms'

a = 650071
b = 276

result = b / a
print(result)

0.00042456900861598197


Male-related terms are mentioned with a relative frequency of .042%

This is comparable with Rainsford's .041% and Edwards' text with a relative frequency of .042%

Out of all the characters counted by SpaCy, female-related terms are mentioned .012% of the time and male-related terms are mentioned .042% of the time. Knowing this, we can see that gendered-language does not make up a large portion of Basket's text. 

Similar to before, by looking at the internal ratios of each gender we can discover if there is a dependant relationship between gender and relational-terms. 

Let's begin by looking at female-related terms. I will create a new list containing all female relational-terms in Basket. 

In [37]:
B_total_female_relational_terms = ['mother', 'mothers', 'wife', 'wives', 'sister', 'sisters', 'daughter', 'daughters']

B_total_female_relational_terms = B_df_female_mentions[B_df_female_mentions['index'].isin(B_total_female_relational_terms)]['Counts'].sum()

print(f"Sum of all Basket female relational terms: {B_total_female_relational_terms}")

Sum of all Basket female relational terms: 52


Alright. Now it's time to find the frequency of female-relational terms used in Basket through simple division. 

In [38]:
a = 'Sum of all Basket female relational terms'
b = 'Sum of all Basket female-related terms'

a = 52
b = 79

result = a / b
print(result)

0.6582278481012658


The female relational ratio is 66%

This is very close to Rainsford's 64%. It also highlights that Edwards' 40% was the lowest out of my subjects

Let's compare this to the male relational ratio.

In [39]:
B_total_male_relational_terms = ['father', 'fathers', 'son', 'sons', 'husband', 'husbands', 'brother', 'brothers']

# Filter the DataFrame for these terms and sum their counts
B_total_male_relational_terms = B_df_male_mentions[B_df_male_mentions['index'].isin(B_total_male_relational_terms)]['Counts'].sum()

print(f"Sum of all Basket male relational terms: {B_total_male_relational_terms}")

Sum of all Basket male relational terms: 101


Now I will discover the male relational ratio and see the frequency of relational male terms such as 'father', 'son', and 'husband'.

In [40]:
a = 'Sum of all Basket male relational terms'
b = 'Sum of all Basket male-related terms'

a = 101
b = 276

result = a / b
print(result)

0.36594202898550726


The frequency of relational male terms is 37%. This is greater than Rainsford's 32% Edwards' 24%.

By using the same chi-square test, the signifiance of relational gendered terms can be understood. The null hypothesis is the same, that there is no relation between gender and relational-terms. We will test for the p-value to determine if there is likely an independant relationship between gender and relational terms.

In [41]:
female_relational = 52
female_nonrelational = 27
male_relational = 101
male_nonrelational = 175

table = pd.DataFrame(
    [[female_relational, male_relational],
     [female_nonrelational, male_nonrelational]],
    index=['relation', 'nonrelational'],
    columns=['female', 'male']
)
display(table)

chi2, p, dof, expected = chi2_contingency(table)
print("chi2:", chi2)
print("p-value:", p)
print("expected:", expected)

,female,male
relation,52,101
nonrelational,27,175


chi2: 20.22097545691985
p-value: 6.899228776384601e-06
expected: [[ 34.04788732 118.95211268]
 [ 44.95211268 157.04788732]]


As we know, a p-value < 0.05 means that the difference between the values is unlikely due to chance. In Basket's text, we can see that the p = 0.0000069. While still not as extream as Raindford, it is *much* stronger than Edwards'. Basket's p-value tells us to reject the null hypothesis, showing that its is unlikely that the relationship between gender and relational-terms is independant. 

By this point, I was not very surpised by the expected values. The trend has been that the expected values for female relational terms and male nonrelational terms to be ~20 words less than the actual amount. The expected values for female nonrelational terms and male relations terms has so been ~20 words more than the actual amount. 

## Basket Gendered Language: Take-Aways

The analysis conducted provides strong evidence in favor of finding gender and relational-terms dependant in Basket's text. Specifically, it shows using quantative means that female-gendered langauge takes up .012% of Basket's total characters. Yet within that .012%, 66% of all occurances use relational-terms such as mother, wife, and sister. Male-related terms are take of .042% of Basket's text. Within that .042%, male relational-terms are used only 37% of the time.

Once again, disporportional representation is apparent in the way female and male gendered-language is used during this specific time period. 

# Conclusion

Now, I will extract the same exact list of terms to ensure continuity between my subjects. Then, I will visualize the most commons female gendered terms used in Edwards' text using pandas. 

In this notebook, I used SpaCy and pandas to tokenize and analyze gendered language in three 19th-century colonial Caribbean texts. For each text, I loaded the source text identified female and male-related terms, computed counts and relative frequencies, separated relational terms from nonrelational terms, calculated relational ratios for each gender, and applied chi-square tests to evaluate whether gender and relational-term usage were independent.

Across Rainsford, Edwards, and Basket, my analysis found that female-related terms appeared less often overall than male-related terms, but a larger portion of female terms were relational (mother, wife, daughter, sister) compared to male terms. 

The chi-square tests in all three texts produced p-values below 0.05, supporting rejection of the null hypothesis. In addition, this signifies a statistically significant association between gender and relational-term usage. The expected values given by the chi-squared test command reported a trend where they would be ~20 words more or less than the actual values. Being able to recongize this trend over 3 different subjects reflects what was found by the chi-square tests. All the p-values proved signifigant and resulted in a rejected null. This means that the claim that gender and relational independant is not very likely at all to be true.

Overall, I have provided a key insight on a historical question using quantitative methodologies. I set out to explore the relationship between gender and relational-terms in early 19th century colonial Caribbean textbooks in order to locate insights on gender norms of the era. I discovered that the relationship between gender and relational terms are dependant. These results show a consistent pattern in the examined colonial texts: women are more frequently represented through relational language than men. Going back to my orginal hypothesis, it shows that women are mentioned in virtue of their relationship to men more often then men are mentioned relationally to women.